### ISSUE TITLE
Bug related to execution monitoring (EFK)

### ISSUE THREAD

**Issue by YemreGurses** [srdc/tofhir#230]
A similar error has been reported from multiple places on the EFK side. After running an execution, execution monitoring screen stucks like below:
![image](https://github.com/user-attachments/assets/b10683e0-376f-407a-9421-06a51bf4a4e2)

[Screencast from 19-09-2024 02_17_19 ΜΜ.webm](https://github.com/user-attachments/assets/d259997e-d8db-480a-98b9-8dc4de6873bb)

We suspect duplicate records as the reason. This error can be received after running mapping with a dataset containing duplicate records.

Probably related to this: https://github.com/srdc/tofhir/issues/198

**Comment by dogukan10** [comment]
First, I can confirm that duplicate records are not the cause of this issue. I tested several scenarios and different environments (Docker, IDE, etc.), but I was unable to reproduce the error.

Previously, we generated `@timestamp` using `System.currentTimeMillis()` as shown below:

```scala
markerMap.put("@timestamp", System.currentTimeMillis.toString)
```

This produced a number like `1729258250148`, which could have been interpreted by Kibana as a string rather than a date. To address this, I’ve modified it to generate a properly formatted string like `2024-10-18T13:38:53.921Z`, which should resolve the issue.

I’m keeping this ticket open for now, in case we encounter the problem again. If it does reoccur, we should retrieve the logs directly from Elasticsearch using its API and investigate the specific `@timestamp` values. If the issue doesn’t reappear, we can close the ticket.
